### ISSUE TITLE
Plz help! no iso file in the ./distroshare

### ISSUE THREAD

**Issue by teddyzxcv** [Distroshare/distroshare-ubuntu-imager#26]
[Issue.txt](https://github.com/Distroshare/distroshare-ubuntu-imager/files/4740520/Issue.txt)
I can't find any error in the process, I work on the pop os and I think that similar to Ubuntu.

**Comment by 0xbuidler** [comment]
same, did you find the problem ?

**Comment by teddyzxcv** [comment]
No, i gave up


Maxime Aubanel <notifications@github.com> 于2020年7月15日周三 下午2:52写道：

**Comment by 0xbuidler** [comment]
I found the solution:

`sudo apt-get install mtools`

**Comment by bigc0127** [comment]
> I found the solution:
> 
> `sudo apt-get install mtools`

this fixed everything, thank you

**Comment by teddyzxcv** [comment]
> I found the solution:
> 
> `sudo apt-get install mtools`
Wow, thank you!!
