### ISSUE TITLE
15.04 Bug?

### ISSUE THREAD

**Issue by ghost** [Distroshare/distroshare-ubuntu-imager#5]
Your script works fine but it does something to GRUB on the user's computer and in the custom distro that they have created with your script.

sudo update-grub displays following message as part of the report:   No volume groups found

Is there a way to fix grub to remove 'No volume groups found' or a way I can customize your script to prevent it's creation?

**Comment by hugegreenbug** [comment]
I think that message must be from LVM being installed. I install it since the installer could use it for encryption if the user selects it. If you remove the lvm2 package, it should go away. You can edit the script so it doesn't install it.

**Comment by ghost** [comment]
I'll be keeping lvm2 now that know what the update-grub message meant. Thanks for the information and the script.
